import React from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from './components/Navbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NavBar/>
      <body className={inter.className}>{children}</body>
      <Footer/>
    </html>
  )
}
